version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                USER: '${DOCKER_USER:-photoalbum}'
                UID: '${DOCKER_UID:-1000}'
                PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT:-100M}
        image: photoalbum
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-develop,debug}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        working_dir: /home/www/photoalbum
        volumes:
            - '.:/home/www/photoalbum'
        networks:
            - photoalbum
        depends_on:
            - nginx
            - node
            - mariadb
            - redis
            - meilisearch
            - selenium
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - .:/home/www/photoalbum
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - photoalbum
    node:
        image: node:lts
        tty: true
        restart: unless-stopped
        ports:
            - 8080:8080
        working_dir: /home/www
        volumes:
            - ./photoalbum_front:/home/www
        networks:
            - photoalbum
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'photoalbum-mariadb:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - photoalbum
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'photoalbum-redis:/data'
        networks:
            - photoalbum
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'photoalbum-meilisearch:/meili_data'
        networks:
            - photoalbum
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - photoalbum
    selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - photoalbum
networks:
    photoalbum:
        driver: bridge
volumes:
    photoalbum-mariadb:
        driver: local
    photoalbum-redis:
        driver: local
    photoalbum-meilisearch:
        driver: local
